---
title: "R Example Plot"
author: "Matthew Perez"
date: "11/18/2022"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r cars, include=FALSE}
library(tidycensus)
options(tigris_use_cache = TRUE)
library(ggiraph)
library(tidyverse)
library(tigris)
library(patchwork)
library(scales)

census_api_key("85df8a378db95eab37d29c343578fe8406959e23")

#Household Income by County fo Texas Region 11

region_11 <- c("Aransas", "Bee", "Brooks", "Cameron", "Duval", "Hidalgo", "Jim Hogg", "Jim Wells", "Kenedy", "Kleberg", "Live Oak",
              "McMullen", "Nueces", "Refugio", "San Patricio", "Starr", "Webb", "Willacy", "Zapata") #Region 11 counties

#Region 11 maps

income_map <- function(x) {

tx_income <- get_acs(
  geography = "county",
  variables = "B19013_001", #household income
  state = "TX",
  year = 2020,
  geometry = TRUE
) %>%
  mutate(NAME = str_remove(NAME, " County, Texas")) %>%
  filter(NAME %in% x)

tx_map <- ggplot(tx_income, aes(fill = estimate)) + 
  geom_sf_interactive(aes(data_id = GEOID)) + 
  scale_fill_distiller(palette = "Blues",
                       direction = 1, 
                       guide = "none") + 
  theme_void()

tx_plot <- ggplot(tx_income, aes(x = estimate, y = reorder(NAME, estimate), 
                                 fill = estimate)) +
  geom_errorbar(aes(xmin = estimate - moe, xmax = estimate + moe)) +
  geom_point_interactive(color = "black", size = 4, shape = 21,
                         aes(data_id = GEOID)) +
  scale_fill_distiller(palette = "Blues", direction = 1,
                       labels = label_dollar()) + 
  scale_x_continuous(labels = label_dollar()) + 
  labs(title = "Household income by county in 'x' ",
       subtitle = "2016-2020 American Community Survey",
       y = "",
       x = "ACS estimate (bars represent margin of error)",
       fill = "ACS estimate") + 
  theme_minimal(base_size = 14)

girafe(ggobj = tx_map + tx_plot, width_svg = 10, height_svg = 5) %>%
  girafe_options(opts_hover(css = "fill:red;"))

}

maps <- income_map(region_11)

```

## Example map

```{r map, echo=FALSE, warning=FALSE}
maps
```

